"""Update QueriesReply to reference StudentDoubt

Revision ID: 03b06c200ffd
Revises: 
Create Date: 2025-03-28 17:18:42.851292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b06c200ffd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QueriesReply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doubt_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'StudentDoubt', ['doubt_id'], ['doubt_id'])
        batch_op.drop_column('query_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('QueriesReply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Queries', ['query_id'], ['query_id'])
        batch_op.drop_column('doubt_id')

    # ### end Alembic commands ###
